//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nomina
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int Id { get; set; }
        public string Cedula { get; set; }
        public string Name { get; set; }
        public double Salary { get; set; }
        public int Position_Id { get; set; }
        public int Department_Id { get; set; }
        public int Payroll_Id { get; set; }
    
        public virtual Position Position { get; set; }
        public virtual Department Department { get; set; }
        public virtual Payroll Payroll { get; set; }
    }
}
